# ----------- CONFIGURABLE START -----------
title:            "paleXu的技术博客"
description:      "一个技术新人的成长之路"
url:              https://palexu.github.io # Site url, without a slash at the end.
signoff:          "palexu" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons
comments:         true
ads:              false

links:
  - name:         文章
    url:          /
    external:     false
  - name:         关于我
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------
my-title:
  first: 鲸
  last: 鱼

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-sitemap